# Generated by Django 6.0 on 2026-01-10 06:20

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usersapp', '0002_alter_user_id_alter_user_photo_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='id',
            field=models.UUIDField(default=uuid.UUID('6a00bd7d-72b1-4ce4-870a-b61ba5a41a5d'), editable=False, primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='userconfirmation',
            name='id',
            field=models.UUIDField(default=uuid.UUID('6a00bd7d-72b1-4ce4-870a-b61ba5a41a5d'), editable=False, primary_key=True, serialize=False, unique=True),
        ),
    ]
